name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Unit Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/lcov.info
    
    - name: Coverage
      uses: codecov/codecov-action@v1.0.14
      with:
        name: Codecov
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
